---
title: "Replication of The Essence of Innocenece: Consequences of Dehumanizing Black Children by Phillip Atibs Goff et. al. (2014, Journal of Personality and Social Psychology)"
author: "Phillip Atibs Goff et. al. (goff@policingequity.org)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

##Introduction

I am a pursuing a joint degree between law and social psychology and am particularly interested in criminal law and inequalities that exist in our criminal justice system. I think it is very important for practicing lawyers--prosecutors, defense attorneys, and judges--to understand the complexities of our biases that, in part, account for the vast racial disparities in our nation's incarceration (e.g. one of every three black men will be incarcerated at some point in their lives). Black men often first enter the criminal justice system as boys and are substantially more likely to do so than their white counterparts. In testing whether children enjoy fewer of the basic human protections afforded to their peers--because the category “children” is seen to be a less essential category when it is applied to black children--Goff et al help illuminate some of the underlying mechanisms at work in the juvenile justice system. While this paper is not from Psychological Science (it's from the Journal of Personality and Social Psychology) it aligns very well with my research interests--attempting to understand the psychological phenomenon that contribute to the . 

The study I want to replicate (study 1) asks participants about the innocence of children by asking questions about how innocent children are in general and how innocent White and Black children are. 123 students participated in the study for college credit. Participants were randomly assigned to one of three conditions (white children, black children, children generally). They filled out a survey which asked them to rate individuals within six age subgroups (0-4, 5-9, 10-13, 14-17, 18-21, 22-25). There were given a set of seven questions which they answered for each of the six age groups within their assigned race (i.e. how much care do 0-4 year old black children need?). Overall ratings of innocence by race were then compared by conducting independent sample t tests on the average score for each participant. 

I choose what I thought was a simple and straightforward study because I have very little experience with R and experimental methods. I think for me, using R will be a challenge. While this does not involve the use of mechanical turk, I think it would be really interesting to run this study on mechanical turk as well and see if the outcome is different. If you think it is important that I replicate a study that originally uses mechanical turk, I am happy to find a different study.  

https://github.com/dspivack/goff2014.git
https://github.com/dspivack/goff2014/tree/master/original_paper

##Methods

###Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

###Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

###Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

###Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

###Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

###Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


##Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
###Data Preparation

####Load Relevant Libraries and Functions

####Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

###Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
